server:
  port: 8080
  ssl:
    enabled: true
    client-auth: want
    key-store: classpath:client.jks
    key-store-password: password
    key-alias: client
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:client.jks
    trust-store-password: password
    trust-store-type: JKS